### ISSUE TITLE
remark-frontmatter not installed?

### ISSUE THREAD

**Issue by Strahinja** [remarkjs/remark-frontmatter#13]
### Subject of the issue

I'm trying to use `remark-frontmatter` in my Nuxt.js project. However, I'm getting a warning in the console during `yarn generate`, even after I installed `remark-frontmatter`.

### Your environment

*   **OS**: Windows 10 x64
*   **Packages**: latest remark-frontmatter (2.0.0)
*   **Env**: node v10.13.0, yarn 1.22.4, latest Vivaldi

### Steps to reproduce

Repository: [Strahinja/remark-bug](https://github.com/Strahinja/remark-bug)

### Expected behaviour

No warnings.

### Actual behaviour

```
WARN  remark-frontmatter,yaml is not installed
```

**Comment by ChristianMurphy** [comment]
@Strahinja this isn't a bug with remark-frontmatter.
Nuxt content currently does not support settings in remark plugins
https://github.com/nuxt/content/blob/0e217dc20d742c0531c69a829e007ab7e9673086/lib/parsers/markdown/index.js#L67-L75

That is why the error is `remark-frontmatter,yaml is not installed` instead of seperating the plugin from the settings it concatenated them together, creating an invalid package name.

**Comment by Strahinja** [comment]
@ChristianMurphy, thank you for the clarification. :)
